Add config options for tls, basic_auth
canonical/prometheus-scrape-target-k8s-operator pull request #21
Opened 2022-09-06 02:10 UTC by sed-i

## Issue
https://github.com/canonical/prometheus-k8s-operator/issues/347

## Solution
Add config options for tls, basic_auth

## Context
NTA

## Testing Instructions
- Manually deploy and relate this and [prom](https://github.com/canonical/prometheus-k8s-operator/pull/351).

## Release Notes
Add config options for tls, basic_auth.

2022-09-08 15:37 UTC, dstathis requested changes

2022-09-08 15:37 UTC, dstathis commented on config.yaml
> +    type: boolean
These descriptions need some attention.

2022-09-09 13:10 UTC, Abuelodelanada requested changes

2022-09-09 13:10 UTC, Abuelodelanada commented on config.yaml
> +    type: boolean
I agree with this comment :P

2022-09-13 13:21 UTC, sed-i commented on config.yaml
> +    type: boolean
Oh my! Fixed.

2022-09-13 13:40 UTC, Abuelodelanada approved these changes

2022-09-13 14:04 UTC, dstathis approved these changes

2022-09-13 14:22 UTC, merged